[device]
device_type = "atecc508a"
# device_type = "bulgulator"
iface_type = "i2c"
# iface_type = "zigzag"
wake_delay = 1500
rx_retries = 20

[interface]
slave_address = 0xc0
# bus = 2
# bus 1 should work with i2c-pseudo
bus = 1
baud = 400000
